name: XCS236
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.2.3
  - requests=2.32.3
  - scipy=1.15.2
  - scikit-learn=1.6.1
  - tensorboard=2.19.0
  - matplotlib=3.10.0
  - tqdm=4.67.1
  - thefuzz=0.22.1
  - seaborn=0.13.2
  - pillow=11.1.0
  - pyyaml=6.0.2
  - pip=25.1
  - pip:
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.7.0; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.7.0+cpu; sys_platform == "linux" or sys_platform == "win32"
    - "--find-links https://download.pytorch.org/whl/torchvision/"
    - torchvision==0.22.0; sys_platform != "linux" and sys_platform != "win32"
    - torchvision==0.22.0+cpu; sys_platform == "linux" or sys_platform == "win32"
    # Manage the below packages over pip to avoid segmentation fault in transformers on Mac
    - datasets==3.6.0
    - numpy==2.2.5
    - memory-profiler==0.61.0
    - diffusers==0.33.1
